### ISSUE TITLE
А где код то?)

### ISSUE THREAD

**Issue by dimmduh** [FirePro/QiwiClient#1]
Где код? Или только на readme хватило)

**Comment by FirePro** [comment]
Потребовал доработки для выкладки на opensource, а потом что-то забросил оставив исходники на компьютере :) Возможно, рабочая библиотека, в ближайшее время появится, а то некоторые разработчики за 200 строк кода требуют 2500 рублей и они шифруют код через ioncube и непонятно, куда могут уйти ваши пароли, не хорошо :)

**Comment by dimmduh** [comment]
Эх, лучше публикуйте как есть)
я не дождался, авторизацию и пополнение баланса на мобильник запилил.
https://twitter.com/ama_programmer
Нужно было пополнить 30 телефонов - до чего лень програмерская доводит)
Тоже надеюсь причешу и выложу код.

**Comment by FirePro** [comment]
Да там все просто при работе с их API, главное с IP других стран не обращаться, иначе включит автоматический SMS авторизацию. У меня весь функционал готовый, его просто причесать надо, стыдно выкладывать :)

**Comment by ampermetr1** [comment]
Код еще выложить нету времени??)

**Comment by dimmduh** [comment]
Там официальное апи есть, правда берут по 2% за перевод (не точно)

**Comment by FirePro** [comment]
Да, прошло много времени, аж 6 лет, а я код так и не выложил))

Пользуйтесь официальным QIWI API: https://developer.qiwi.com/ 

Тогда такой возможности не было и надо было писать либу, а щас необходимости в этом нет.
